### PR TITLE
bump to latest @esri/request

### PR DESCRIPTION
**Pull request by jgravois**
`v1.6.0` > `v1.2.1`

### CODE REVIEW

**Comment by tomwayson** [comment]
just me, or does this only include the yarn.lock file and not package.json?

**Comment by jgravois** [comment]
_too_ SemVer?

**Comment by tomwayson** [comment]
wow. just wow.

we should bump in cedar then, no?

**Comment by tomwayson** [comment]
Addressed in https://github.com/Esri/ember-cli-cedar/pull/101/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R28

**Pull request closed without merging**
